/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

/**
 *
 * @author celio_henrique
 */
public class MarcaGui extends javax.swing.JFrame {

    /**
     * Creates new form MarcaGui
     */
    public MarcaGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Paneil1 = new javax.swing.JPanel();
        LbInserirMarcas = new javax.swing.JLabel();
        LbNomeMarcas = new javax.swing.JLabel();
        BtSalvar = new javax.swing.JButton();
        BtLimpar = new javax.swing.JButton();
        TxtMarcasNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbInserirMarcas.setText("Inserir Marcas");

        LbNomeMarcas.setText("Marcas");

        BtSalvar.setText("Salvar");

        BtLimpar.setText("Limpar");
        BtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Paneil1Layout = new javax.swing.GroupLayout(Paneil1);
        Paneil1.setLayout(Paneil1Layout);
        Paneil1Layout.setHorizontalGroup(
            Paneil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Paneil1Layout.createSequentialGroup()
                .addGroup(Paneil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Paneil1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LbInserirMarcas))
                    .addGroup(Paneil1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbNomeMarcas)
                        .addGap(27, 27, 27)
                        .addComponent(TxtMarcasNome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Paneil1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(BtSalvar)
                        .addGap(46, 46, 46)
                        .addComponent(BtLimpar)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        Paneil1Layout.setVerticalGroup(
            Paneil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Paneil1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbInserirMarcas)
                .addGap(44, 44, 44)
                .addGroup(Paneil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeMarcas)
                    .addComponent(TxtMarcasNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(Paneil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalvar)
                    .addComponent(BtLimpar))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Paneil1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Paneil1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcaGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtLimpar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JLabel LbInserirMarcas;
    private javax.swing.JLabel LbNomeMarcas;
    private javax.swing.JPanel Paneil1;
    private javax.swing.JTextField TxtMarcasNome;
    // End of variables declaration//GEN-END:variables
}
